name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Compile host example
      run: |
        pushd test
        make host_test
        popd
    - name: Install dependencies
      run: |
        sudo apt install gdb
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        ./test/host_test &
        pid=$!
        python -m unittest -v test/test_*.py
        kill -SIGTERM $!
